language: python
python:
- '3.6'
- '3.7'
- '3.8'
cache:
  directories:
  - build
install:
- pip install -U -r test_requirements.txt
- pip install --no-deps -e .
script:
- black --check smlb -l 99
- pytest tests
