language: python
python:
- '3.6'
- '3.7'
- '3.8'
cache:
  directories:
  - build
install:
- pip install -U -r test_requirements.txt
- pip install --no-deps -e .
script:
- black --check smlb -l 99
- pytest tests
deploy:
- provider: pypi
  user: "CitrineInformatics"
  password: "$PYPI_PASSWORD"
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true

env:
  global:
    - secure: 
